### ISSUE TITLE
type mismatch between u1 and bool should be the same type

### ISSUE THREAD

**Issue by sanket1729** [BlockstreamResearch/simfony#108]
```
thread 'tests::ctv_2' panicked at src/lib.rs:271:31:
   |
74 |     let (carry, time_elapsed) : (u1, u32) = jet::subtract_32(curr_time, time_at_broadcast);
   |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Expected expression of type `(u1, u32)`, found type `(bool, u32)`
```

**Comment by apoelstra** [comment]
In principle, `bool` is a "truth value" while `u1` is "an integer mod 2".

I could go either way on conflating these types.

At the very least, we should improve the error message to tell the user how to do the conversion. I *think* you can just do `.into()` on the whole thing because `(u1, u32)` and `(bool, u32)` have the same representation.
